name: Build & Release

on:
    workflow_dispatch:
        inputs:
            draftRelease:
                description: Creates a new release draft based on the build.
                required: false
                type: boolean

jobs:
    build:
        name: Build
        runs-on: windows-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                submodules: 'recursive'
            
            - name: Setup dotnet
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 8.x
                dotnet-quality: ga

            - name: Install OpenVR Dependencies
              shell: cmd
              run: |
                call cd EasyOpenVR
                call download_openvr_api_dependencies.cmd

            - name: Install dependencies
              run: dotnet restore
              
            - name: Build
              run: dotnet build --configuration Release